added experimental selection screencast support

diff --git a/teiler b/teiler
--- a/teiler
+++ b/teiler
@@ -28,7 +28,7 @@ mainMenu () {
         0:*) exit ;;
         1.*) delayPrompt screenshot -d ;;
         2.*) delayPrompt screenshot -s -d ;;
-        3.*) isRecording && stopRecording && sleep 2 && askPrompt || screencast ;;
+        3.*) isRecording && stopRecording && sleep 2 && askPrompt || screencastPrompt ;;
         4.*) imgClip ;;
         5.*) clipUpload ;;
         6.*) uploadMenu ;;
@@ -119,6 +119,42 @@ screencast () {
     indicator
     notify "$time" "Screencast started"
 }
+
+screencastPrompt() {
+    menu=("0: << back to Main Menu"
+          "---"
+          "1. Fullscreen"
+          "2. Area")
+
+    prompt() {
+        printf "%s\n" "$@" | dmenu_t -p "Upload:"
+    }
+
+       case "$(prompt "${menu[@]}")" in
+       0:*) mainMenu ;;
+       1.*) screencast ;;
+       2.*) screencastArea ;;
+         *) mainMenu
+   esac
+}
+
+
+screencastArea () {
+    type avconv || type ffmpeg &>/dev/null || { echo "Missing Dependencies"; exit 1; }
+    isRecording && {
+        notify "$time" 'Screencast already in progress'
+        echo "Already recording Screen"; exit 1;
+}
+    rectangle=$(xrectsel)
+    rectangle2=$(echo $rectangle | awk -F '+' '{ print $2, $NF }' | sed -e 's/ /,/g')
+    rectangle1=$(echo $rectangle | awk -F '+' '{ print $1 }')
+    [[ -f "${vid_path}/lastvid.mp4" ]] && rm "${vid_path}/lastvid.mp4"
+    $encoder -f x11grab -s $rectangle1 -i $ffmpeg_display+$rectangle2 $ffaudio $encopts "${vid_path}/lastvid.mp4" &
+    echo "$!" > "$SCREENCAST_PIDFILE"
+    indicator
+    notify "$time" "Screencast started"
+}
+
 
 isRecording () {
     [[ -f "$SCREENCAST_PIDFILE" ]] || return 1;
