Added screencasting of windows

diff --git a/teiler b/teiler
--- a/teiler
+++ b/teiler
@@ -128,7 +128,8 @@ screencastPrompt() {
     menu=("0: << back to Main Menu"
           "---"
           "1. Fullscreen"
-          "2. Area")
+          "2. Window"
+          "3. Area")
 
     prompt() {
         printf "%s\n" "$@" | dmenu_t -p "Screencast:"
@@ -137,7 +138,8 @@ screencastPrompt() {
        case "$(prompt "${menu[@]}")" in
        0:*) mainMenu ;;
        1.*) screencast ;;
-       2.*) screencastArea ;;
+       2.*) screencastWindow ;;
+       3.*) screencastArea ;;
          *) mainMenu
    esac
 }
@@ -158,6 +160,24 @@ screencastArea () {
     indicator
     notify "$time" "Screencast started"
 }
+
+screencastWindow () {
+    type avconv || type ffmpeg &>/dev/null || { echo "Missing Dependencies"; exit 1; }
+    isRecording && {
+        notify "$time" 'Screencast already in progress'
+        echo "Already recording Screen"; exit 1;
+}
+    rectangle=$(xwininfo | grep geometry | awk -F '-geometry ' '{ print $2 }')
+    rectangle2=$(echo $rectangle | awk -F '+' '{ print $2, $NF }' | sed -e 's/ /,/g')
+    rectangle1=$(echo $rectangle | awk -F '+' '{ print $1 }')
+    [[ -f "${vid_path}/lastvid.mp4" ]] && rm "${vid_path}/lastvid.mp4"
+    $encoder -f x11grab -s $rectangle1 -i $ffmpeg_display+$rectangle2 $ffaudio $rect_encopts "${vid_path}/lastvid.mp4" &
+    echo "$!" > "$SCREENCAST_PIDFILE"
+    indicator
+    notify "$time" "Screencast started"
+}
+
+
 
 screencastInputArea () {
     type avconv || type ffmpeg &>/dev/null || { echo "Missing Dependencies"; exit 1; }
