changed dependencies from simpleswitcher to rofi

diff --git a/teiler b/teiler
--- a/teiler
+++ b/teiler
@@ -297,15 +297,15 @@ x_clip () {
 ################################################################################################################
 
 
-type dmenu &>/dev/null || type simpleswitcher &>/dev/null || { echo "Missing Dependencies"; exit 1; }
+type dmenu &>/dev/null || type rofi &>/dev/null || { echo "Missing Dependencies"; exit 1; }
 
 
 source "$HOME/.config/teiler/config"
 source "$HOME/.config/dmenurc"
 
-if [[ "$backend" == "simpleswitcher" ]]
+if [[ "$backend" == "rofi" ]]
     then function dmenu_t () {
-    simpleswitcher -font "$font" -fg "$nf" -bg "$nb" -hlfg "$sf" -hlbg "$sb" -o 90 -bc "$bc" -dmenu "$@"
+    rofi -font "$font" -fg "$nf" -bg "$nb" -hlfg "$sf" -hlbg "$sb" -o 90 -bc "$bc" -dmenu "$@"
 }
 
 elif [[ "$backend" == "dmenu" ]]
