cleaned spacings a bit

diff --git a/teiler b/teiler
--- a/teiler
+++ b/teiler
@@ -91,19 +91,19 @@ delayPrompt () {
 }
 
 delayCountdown () {
-for ((n=${1:-t}; n>=0; --n)); do
-printf "\n%s " $n
-sleep 1
-done
-printf "\r \r"  # clean up
+    for ((n=${1:-t}; n>=0; --n)); do
+        printf "\n%s " $n
+        sleep 1
+    done
+    printf "\r \r"  # clean up
 }
 
 delayClip () {
-for ((n=${1:-10}; n>=0; --n)); do  
-  printf "\n%s " $n
-  sleep 1
-done
-printf "\r \r"  # clean up
+    for ((n=${1:-10}; n>=0; --n)); do  
+        printf "\n%s " $n
+        sleep 1
+    done
+    printf "\r \r"  # clean up
 }
 
 imgClip () {
@@ -118,7 +118,7 @@ isRecording () {
 }
 
 screenshot () {
-     type scrot &>/dev/null || { echo "Missing scrot!"; exit 1; }
+    type scrot &>/dev/null || { echo "Missing scrot!"; exit 1; }
     [[ -f "${img_path}/lastimg.png" ]] && rm "${img_path}/lastimg.png"
     scrot "$@" "${img_path}/lastimg.png"
     notify "$time" "Screenshot saved"
@@ -171,12 +171,12 @@ upLoad () {
 instantUpload () {
     if [[ $1 == png ]]
         then file=$(readlink "$img_path/lastimg.png")
-             type="Image"
+        type="Image"
     elif [[ $1 == webm ]]
         then file=$(readlink "$img_path/lastvid.webm")
-             type="Video"
+        type="Video"
     fi
-        if [[ "$ul" == scp ]]
+    if [[ "$ul" == scp ]]
         then scp "$file" "$scp_host":/"$2/"
         notify-send "$(echo $type) Uploaded" "$3/$(basename "$file")"
         echo -n "$3/$(basename "$file")" | xclip
@@ -199,13 +199,13 @@ source "$HOME/.config/teiler/config"
 
 if [[ "$backend" == "simpleswitcher" ]]
     then function dmenu_t () {
-        simpleswitcher -font "$font" -fg "$nf" -bg "$nb" -hlfg "$sf" -hlbg "$sb" -o 90 -bc "$bc" -dmenu "$@"
-        }
+    simpleswitcher -font "$font" -fg "$nf" -bg "$nb" -hlfg "$sf" -hlbg "$sb" -o 90 -bc "$bc" -dmenu "$@"
+}
 
 elif [[ "$backend" == "dmenu" ]]
-            then function dmenu_t () {
-            dmenu -l 15 -fn "$font" -nf "$nf" -nb "$nb" -sf "$sf" -sb "$sb" -o 90 "$@"
-            }
+    then function dmenu_t () {
+    dmenu -l 15 -fn "$font" -nf "$nf" -nb "$nb" -sf "$sf" -sb "$sb" -o 90 "$@"
+}
 fi
 
 mainMenu
